# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test01(self):
    # Test name: Test01
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1042x554 | 
    self.driver.set_window_size(1042, 554)
    # 3 | type | name=q | python
    self.driver.find_element(By.NAME, "q").send_keys("python")
    # 4 | click | css=form > div:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(1)").click()
    # 5 | click | css=center:nth-child(1) > .gNO89b | 
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
    # 6 | click | css=.eKjLze .LC20lb | 
    self.driver.find_element(By.CSS_SELECTOR, ".eKjLze .LC20lb").click()
    # 7 | close |  | 
    self.driver.close()
  
